/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.j3lte.geojson;

import java.io.File;
import java.io.IOException;
import java.nio.charset.Charset;

import org.geotools.data.shapefile.ShapefileDataStore;
import org.geotools.data.store.ContentFeatureCollection;
import org.geotools.data.store.ContentFeatureSource;
import org.geotools.geojson.feature.FeatureJSON;
import org.geotools.geojson.geom.GeometryJSON;

public class Library {

    public static boolean loadFile(String inPath, String outPath) throws IOException {
        boolean result = false;
        System.out.println("Loading file: " + inPath);

        ShapefileDataStore dataStore = new ShapefileDataStore(new File(inPath).toURI().toURL());
        dataStore.setCharset(Charset.forName("UTF-8"));

        ContentFeatureSource featureSource = dataStore.getFeatureSource();
        ContentFeatureCollection featureCollection = featureSource.getFeatures();

        FeatureJSON featureJSON = new FeatureJSON(new GeometryJSON(15));
        featureJSON.writeFeatureCollection(featureCollection, new File(outPath));

        dataStore.dispose();
        result = true;

        return result;
    }
}
